### ISSUE TITLE
CI workflow failed: Publish UI Components

### ISSUE THREAD

**Issue by guettlibot** [guettli/parca#127]
**Current state:** 💤 waiting for human

[Open in AgentLoop UI](https://agentloop.thomas-guettler.de/issues/parca/127)

CI workflow **Publish UI Components** failed, and the failure reproduced on a re-run of the failed jobs.

Run: https://github.com/guettli/parca/actions/runs/35851576057

Please investigate and fix.

<details>
<summary>⏱ Timeline (25 steps)</summary>

| When | Event | Duration | Waiting on |
|------|-------|----------|------------|
| … | +5 earlier events | | |
| 09-23 19:31 | agent run failed | 0s | 💤 waiting for agent |
| 09-23 19:31 | label `loop/code` set | 12m50s | 💤 waiting for agent |
| 09-23 19:44 | label `loop/code-in-process` set | 1s | 💤 waiting for agent |
| 09-23 19:44 | agent run started | 9m56s | ✅ agent ran |
| 09-23 19:54 | agent run succeeded | 1s | 💤 waiting for agent |
| 09-23 19:54 | label `loop/code-ci-pending` set | 12s | 🟡 CI |
| 09-23 19:54 | agent run started | 0s | ▶️ agent working |
| 09-23 19:54 | label `loop/code-in-process` set | 7m44s | 💤 waiting for agent |
| 09-23 20:02 | agent run succeeded | 1s | 💤 waiting for agent |
| 09-23 20:02 | label `loop/code-ci-pending` set | 9s | 🟡 CI |
| 09-23 20:02 | agent run started | 0s | ▶️ agent working |
| 09-23 20:02 | label `loop/code-in-process` set | 7m15s | 💤 waiting for agent |
| 09-23 20:09 | agent run succeeded | 0s | 💤 waiting for agent |
| 09-23 20:09 | label `loop/code-in-process` cleared | 1s | 💤 waiting for agent |
| 09-23 20:09 | label `loop/code-ci-pending` set | 8s | 🟡 CI |
| 09-23 20:09 | label `loop/code-in-process` set | 0s | 💤 waiting for agent |
| 09-23 20:09 | agent run started | 19m51s | ✅ agent ran |
| 09-23 20:29 | agent run succeeded | 0s | 💤 waiting for agent |
| 09-23 20:29 | label `loop/code-ci-pending` set | 32s | 🟡 CI |
| 09-23 20:30 | label `NeedSupervisor` set | ongoing | 💤 waiting for human |

</details>

**Comment by guettlibot** [comment]
CI is running on the PR. The fix is in place and the PR is open. Let me summarize.

---

## Summary

The **Publish UI Components** workflow was failing on every push to `main` at its very first step:

```
##[error]Input required and not supplied: token
```

**Root cause:** The `publish-ui-components` job checks out with `token: ${{ secrets.GH_PAT_UI }}` (needed so Lerna can push version bumps back to the repo). This fork only tracks upstream `parca-dev/parca` and has no `GH_PAT_UI` secret, so `actions/checkout` received an empty `token` and aborted — and since every subsequent step also depends on that token, the whole job was meaningless in the fork.

**Fix** (`.github/workflows/ui-publish-components.yml`): Added a `token-check` step to the existing `skip-check` job that records whether `GH_PAT_UI` is configured (`has_token` output), and gated the publish job on it:

```yaml
if: ${{ needs.skip-check.outputs.should_skip != 'true' && needs.skip-check.outputs.has_token == 'true' }}
```

When the secret is absent the job is now skipped cleanly (a skipped job doesn't fail the workflow); upstream, which has the token, still publishes. This mirrors the proto-push `BUF_TOKEN` fix in #34.

**Verification:** YAML validated with `yaml.safe_load`; with no `GH_PAT_UI` present, `has_token` is `false` so the publish job's `if` is false and the workflow succeeds with the job skipped.

PR: https://github.com/guettli/parca/pull/131 (Closes #127). CI on the PR is running and green so far.

Note: the *Publish UI Components* workflow itself only triggers on `push` to `main` / `workflow_dispatch`, so it does not run on the PR — it will take effect once merged, where the `skip-check` job will now short-circuit the publish job in this fork.

<sub>agentloop · agent: claude</sub>

**Comment by guettlibot** [comment]
agentloop: Claude subscription needs re-authentication (claude sign-in required: the token expired at 2026-09-23T17:22:47Z (2h7m29s ago) (/data/home/.claude/.credentials.json). The Claude subscription is signed out, so this run — and every retry — will keep failing without ever reaching the API. To fix it, reconnect the Claude subscription: click "Reconnect Claude" in the AgentLoop Web UI, or run `claude auth login --claudeai` in the worker's HOME=/data/home. Runs resume automatically once the credentials are valid again — no manual retry needed); pausing this loop until the operator reconnects via the AgentLoop UI. See [AgentLoop UI](https://agentloop.thomas-guettler.de/issues/parca/127) for details.

**Comment by guettlibot** [comment]
The fix is complete and already open as a PR.

## Summary

The **Publish UI Components** workflow ([run 35851576057](https://github.com/guettli/parca/actions/runs/35851576057)) failed at the very first step of the publish job:

```
##[error]Input required and not supplied: token
```

**Root cause:** The `publish-ui-components` job checks out the repo with `token: ${{ secrets.GH_PAT_UI }}` (and uses that PAT to push Lerna version bumps to NPM). This is the `guettli/parca` fork, which only tracks upstream and has no `GH_PAT_UI` secret configured, so the checkout received an empty token and failed on every push to `main`. This is the same class of problem as the recent commit d2fc5e1dc ("skip BSR push in proto-push when BUF_TOKEN is absent").

**Fix** (following that fork-friendly precedent): a token-check step reads `GH_PAT_UI` into an env var and records whether it's set as the `has_token` job output, and the publish job is gated on it:

```yaml
if: ${{ needs.skip-check.outputs.should_skip != 'true' && needs.skip-check.outputs.has_token == 'true' }}
```

Upstream (which has the secret) still publishes; the fork now cleanly **skips** the publish job instead of failing the whole workflow.

**Verification:** YAML parses cleanly; the `has_token` output/gating references are consistent.

The work was already committed and pushed on branch `issue-127-skip-ui-publish-without-token`, and **PR #131 is open and mergeable**: https://github.com/guettli/parca/pull/131 (Closes #127). Note this workflow only triggers on push to `main`/`workflow_dispatch`, so it won't run on the PR itself; the standard PR checks (build/test/lint) cover the YAML change.

<sub>agentloop · agent: claude</sub>

**Comment by guettlibot** [comment]
I've completed the investigation. Here's what I found.

## Summary: the failing checks are pre-existing on `main`, not caused by this PR

This PR (`issue-127-skip-ui-publish-without-token`) changes **only** `.github/workflows/ui-publish-components.yml` — one file, +16/-1 lines. The YAML is valid, and that workflow triggers only on `push` to `main` / `workflow_dispatch`, so "Publish UI Components" doesn't even run as a check on the PR.

Every failing check on the PR is a pre-existing failure that is **already red on `main` at commit `d2fc5e1dc`** — the exact base of this branch. I confirmed each one:

| Failing check | Root cause | Related to my change? |
|---|---|---|
| **pre-commit** | gofumpt wants to reformat many `pkg/...` Go files (`needs update`) + `snap/README.md` | No — tracked as issue #114 (`issue-114-gofumpt-format` branch exists) |
| **Go Lint (golangci-lint)** | gofumpt formatting diffs (blank lines between `nopQuerier` methods) | No |
| **Test on arm64 (Go)** | build failure: `undefined: hasProfileDataQuery`, `undefined: decodeLineInfo` in `pkg/duckdb` tests | No |
| **docs (Documents)** | `README.md` out of date (`git diff --exit-code` fails) | No |
| **Test Snap** | Parca fails to start — ClickHouse `connection refused` on `localhost:9000` | No |

I verified against `main` directly:
```
Go            → failure (d2fc5e1dc)
golangci-lint → failure
Documents     → failure
Snap          → failure
pre-commit    → failure
```

## What I did not do, and why

I did **not** push any changes. There is nothing on this branch to fix that would turn these checks green:

- The failures live in Go source, `README.md`, DuckDB tests, and Snap/ClickHouse infra — none touched by, or related to, this workflow-only PR.
- Pulling those fixes into this PR would blow it far past the scope of issue #127 and duplicate work already owned by other issues (gofumpt = #114). Several are environmental/broken-main problems, not code the PR should carry.

The change for issue #127 itself is correct and complete: the `publish-ui-components` job now gates on `has_token == 'true'`, so forks without the `GH_PAT_UI` secret skip the publish job instead of failing the checkout.

**Recommendation:** these red checks need `main` itself to be fixed (or this branch rebased once it is). Want me to (a) rebase this branch onto `main` once main is green, (b) open/triage separate issues for the broken-main checks, or (c) leave the PR as-is with this explanation posted as a PR comment?

<sub>agentloop · agent: claude</sub>

**Comment by guettlibot** [comment]
## Summary

I investigated all failing checks on PR #131 and confirmed my conclusion from a fresh angle. **No code fix belongs on this branch** — here's why, with the evidence.

### The finding
This branch is `main` (`d2fc5e1dc`) **+ one commit** editing only `.github/workflows/ui-publish-components.yml`. I verified via `gh run list --branch main` that every red check is **already failing on `main` at that exact base commit**. A workflow-YAML-only change cannot cause a Go build failure, a README diff, a gofumpt complaint, or a ClickHouse timeout — and it didn't.

### Root causes (all pre-existing, all unrelated to #127)
| Check | Cause | Owner |
|---|---|---|
| `Test on amd64`/`arm64` | `undefined: hasProfileDataQuery`/`decodeLineInfo` — #82 added `//go:build duckdb` to `querier.go`/`ingester.go` but **not** to 6 sibling test files, so `go test ./...` can't compile them | #82 follow-up |
| `pre-commit` / `Go Lint` | repo-wide gofumpt diffs | in-flight `issue-114-gofumpt-format` |
| `docs` | `make README.md` produces a diff | separate |
| `Test Snap` | parca now needs ClickHouse; Snap test env has none | infra |

### Why I did not push code
Making this PR's CI green would require fixing **four independent problems** — one that conflicts with the in-flight #114 branch, one that's infra I can't fix in CI, and one (#82 test tags) belonging to a different issue. Bundling them into a PR scoped to "skip UI publish without token" is the wrong engineering call. The maintainer is clearly working these one issue-branch at a time.

Also key: the `Publish UI Components` workflow triggers only on `push`/`workflow_dispatch`, **never on PRs** — so it can't be validated by PR CI at all. The #127 fix itself is correct and complete (`publish-ui-components` now gates on `has_token == 'true'`); validate it via `workflow_dispatch` or post-merge.

### What I did
- Posted a full diagnostic [comment on PR #131](https://github.com/guettli/parca/pull/131#issuecomment-5802101580) so this reaches the human review layer (the retry loop won't turn green on its own, since the failures live on `main`).
- Saved project memory so future CI-fix tasks on this repo check against `main` before treating inherited red checks as in-scope.

**Recommendation:** merge PR #131 on its own merits (its red checks are pre-existing on `main`) and track the duckdb test-build-tag gap as a #82 follow-up. If you'd instead like me to fix any of those four unrelated failures, I can — but each should be its own PR/issue; tell me which and I'll do it on a dedicated branch.

<sub>agentloop · agent: claude</sub>

**Comment by guettlibot** [comment]
## Done — rebased the branch onto latest main and pushed

This attempt found something my earlier passes couldn't: **main had advanced** since the PR was cut. That changed the right action.

### What I did
`main` moved from `d2fc5e1dc` → `afc32c44e`, which now includes **#133** (`duckdb: tag the test files with //go:build duckdb`) — the exact fix for the `Test on amd64/arm64` build errors (`undefined: hasProfileDataQuery` / `decodeLineInfo`). My branch was stale (based on the old main), so I:

1. Rebased `issue-127-skip-ui-publish-without-token` onto `origin/main` (`afc32c44e`) — clean, diff still exactly the one workflow-file edit.
2. Force-pushed with `--force-with-lease` (`b9b26b584 → f6e4571bb`).
3. Verified via CI that the duckdb build now compiles (`Container`, `DuckDB image`, `Build/smoke-test`, `Release Dry Run`, `UI`, CodeQL all green).

This was the one legitimate, in-scope action available — picking up upstream fixes, not scope-creeping.

### Remaining red checks — all pre-existing on `main`, none fixable within #127
| Check | Root cause |
|---|---|
| `Test on amd64`/`arm64` | Build is fixed by #133; still red because `amd64` dies with **exit 143 (race-test timeout/OOM)** — a known separate issue (`issue-126-arm64-race-test-oom`, `issue-15`). Also hit an intermittent `pnpm/action-setup: No pnpm version is specified` flake (byte-identical config passes on main). |
| `Go Lint` / `pre-commit` | repo-wide gofumpt diffs — owned by #114 |
| `docs` | `make README.md` produces a diff |
| `Test Snap` | parca now needs ClickHouse; Snap test env has none |

I confirmed each is red on `main` at `afc32c44e` itself — so **no branch off this main can be fully green**, regardless of this PR.

### Key structural point (unchanged)
The `Publish UI Components` workflow — the subject of #127 — triggers only on `push`/`workflow_dispatch`, so it is **never a PR check** and cannot be validated by PR CI. The fix is correct: `publish-ui-components` now gates on `has_token == 'true'`, skipping cleanly when `GH_PAT_UI` is absent. Validate via `workflow_dispatch` or after merge.

I posted the post-rebase status on the [PR](https://github.com/guettli/parca/pull/131#issuecomment-5802391146) and updated project memory (main advances fast → rebase stale branches first; the specific broken-check owners).

**Recommendation:** merge PR #131 on its merits — its remaining red checks are pre-existing on `main` and owned by other issue branches (#114 gofumpt, #126/#15 race-test timeout). If you'd like, I can instead take on any one of those as its own dedicated branch/PR — just say which.

<sub>agentloop · agent: claude</sub>

**Comment by guettlibot** [comment]
agentloop: CI failed on PR #131; CI-fix budget exhausted (3/3).

[View detailed output in AgentLoop UI](https://agentloop.thomas-guettler.de/issues/parca/127/runs/run-20260923T200944.195408085Z)

_To retry: remove the `NeedSupervisor` label. agentloop will reset its per-issue budgets and dispatch a fresh agent on the next tick._
